name = "fileshare"
main = "./src/index.js"
compatibility_date = "2022-11-08"
route = "file.mistyhill.ml/*"

kv_namespaces = [
  { binding = "LINK", id = "129af8af9d0f4b3f87e38d68b1d63fa0", preview_id='129af8af9d0f4b3f87e38d68b1d63fa0'}
]


[site]
bucket = "./static/dist"

